#!/bin/bash
#	autosubmitter for single node hex jobs

SCRIPT="$1";
EXEC="$2";
INPUT="$3";
THREADS="$4";
PARTMIN="$5";
PARTMAX="$6";
RUNS="$7";

XNAME=`basename "$EXEC"`;
NAME="${XNAME}-${THREADS}";
qsub	-v "EXEC=\"${EXEC}\",INPUT=\"${INPUT}\",THREADS=\"${THREADS}\",PARTMIN=\"${PARTMIN}\",PARTMAX=\"${PARTMAX}\",RUNS=\"${RUNS}\""\
		-e "data/out/${NAME}.err"\
		-o "data/out/${NAME}.out"\
		-N "${NAME}"\
		-l nodes="1:hex:f2.66:ppn=24" "$SCRIPT";
